name: Convert Web to APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build APK from Web Files
        uses: darkshredder/website-to-apk-action@v1.1.0
        with:
          # This is the folder where your index.html is located
          # If it's in the main folder, just use "./"
          build-folder-path: "./"
          app-name: "MyAIApp"
          output-folder-path: "output-apk/"

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: My-Android-App
          path: output-apk/
